on: push
name: Build, Test, and Publish if master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
   
    - name: Build
      uses: ianwalter/puppeteer@master
      with:
        entrypoint: npm
        args: install
    - name: Test
      uses: ianwalter/puppeteer@master
      with:
        entrypoint: npm
        args: test
    - name: Publish
      if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/bent'
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - uses: mikeal/bundle-size-action@master
      if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/bent'
    - uses: mikeal/publish-to-github-action@master
      if: github.ref == 'refs/heads/master' && github.repository == 'mikeal/bent'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
